// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: fact_checking.proto

package fact_checking

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FactChecking_Check_FullMethodName = "/fact_checking.FactChecking/Check"
)

// FactCheckingClient is the client API for FactChecking service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FactCheckingClient interface {
	Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckListResponse, error)
}

type factCheckingClient struct {
	cc grpc.ClientConnInterface
}

func NewFactCheckingClient(cc grpc.ClientConnInterface) FactCheckingClient {
	return &factCheckingClient{cc}
}

func (c *factCheckingClient) Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckListResponse)
	err := c.cc.Invoke(ctx, FactChecking_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FactCheckingServer is the server API for FactChecking service.
// All implementations must embed UnimplementedFactCheckingServer
// for forward compatibility.
type FactCheckingServer interface {
	Check(context.Context, *CheckRequest) (*CheckListResponse, error)
	mustEmbedUnimplementedFactCheckingServer()
}

// UnimplementedFactCheckingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFactCheckingServer struct{}

func (UnimplementedFactCheckingServer) Check(context.Context, *CheckRequest) (*CheckListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedFactCheckingServer) mustEmbedUnimplementedFactCheckingServer() {}
func (UnimplementedFactCheckingServer) testEmbeddedByValue()                      {}

// UnsafeFactCheckingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FactCheckingServer will
// result in compilation errors.
type UnsafeFactCheckingServer interface {
	mustEmbedUnimplementedFactCheckingServer()
}

func RegisterFactCheckingServer(s grpc.ServiceRegistrar, srv FactCheckingServer) {
	// If the following call pancis, it indicates UnimplementedFactCheckingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FactChecking_ServiceDesc, srv)
}

func _FactChecking_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FactCheckingServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FactChecking_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FactCheckingServer).Check(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FactChecking_ServiceDesc is the grpc.ServiceDesc for FactChecking service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FactChecking_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fact_checking.FactChecking",
	HandlerType: (*FactCheckingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _FactChecking_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fact_checking.proto",
}
