server:
  http:
    addr: :8000
    timeout: 900s

trace:
  otel_state: enable
  sample_ration: 1.0

pyroscope:
  state: enable

project:
  mode: dev

chatmodel:
  model: gpt-4o-mini
  baseURL: https://api.openai.com/v1
  
service:
  checking: Majula.Service.Checking